### ISSUE TITLE
SignIn app changes page url on sign in button press

### ISSUE THREAD

**Issue by miyconst** [StarcounterSamples/SignIn#10]
After changes from @warpech:

https://github.com/StarcounterSamples/SignIn/commit/67d8a68636ad52b15e83dfed7bdd96d29f0f170e#diff-13b0b2de614e7894baa826c4e4e4bef0R74
https://github.com/StarcounterSamples/SignIn/commit/67d8a68636ad52b15e83dfed7bdd96d29f0f170e#diff-13b0b2de614e7894baa826c4e4e4bef0R91

SignIn app changes browser url when signing in/out. This is wrong, as those url can't be accessed directly and throw error in this case.

This leads to:

1. User loses his url after signing in/out.
2. If user presses f5 or reloads page any other way, then error appears.
3. Password provided by user is instantly visible in the address bar.

**Comment by warpech** [comment]
I agree, thanks for noticing. I reverted how it worked previously.

In the long term this should be sent as a POST request, but I didn't manage to do this in short time.

**Comment by miyconst** [comment]
Thanks for fixing it.
