### ISSUE TITLE
Allow disabling call to AssureAdminSystemUser()

### ISSUE THREAD

**Issue by per-samuelsson** [StarcounterSamples/SignIn#11]
As an example, in a set of replicating databases, that kind of assuring is not always what you want. I might want one database to act "master" of users, and all other slaves, and if I should start a slave before the assuring was done on the master, it will cause duplicates.

**Comment by per-samuelsson** [comment]
Related general (internal) discussion: https://github.com/Starcounter/CompanyTrack/issues/179

**Comment by miyconst** [comment]
I have disabled auto admin user generation. It is possible to generate the user by opening `/signin/generateadminuser`. The handler generates the user only if there is no users in database.

Readme is also updated. Closing the issue.
