### ISSUE TITLE
Increase security of SignIn app, the cookie should be used only once

### ISSUE THREAD

**Issue by miyconst** [StarcounterSamples/SignIn#13]
The SignIn cookie should be destroyed as soon as used and a new one should be issued.

**Comment by miyconst** [comment]
Reported by @malx122.

**Comment by warpech** [comment]
Rationale and good practices for this are discussed here: http://stackoverflow.com/questions/22965067/when-and-why-i-should-use-session-regenerate-id

**Comment by miyconst** [comment]
SignIn app now resets auth-cookie value on each authenticated request.
