### ISSUE TITLE
Do not send password as plain text

### ISSUE THREAD

**Issue by miyconst** [StarcounterSamples/SignIn#15]
It is insecure to send password from client side to server side via plain text. The password should be hashed.

**Comment by miyconst** [comment]
Reported by @malx122.

**Comment by miyconst** [comment]
Password is now double hashed. All existing users should be created again.

**Comment by atifwaqar** [comment]
@miyconst I just cleaned my DB, Created the users again, and i still have the same issue. as explained in [31](https://github.com/StarcounterSamples/SignIn/issues/31)

Do you think my User Creation have some issue?

**Comment by miyconst** [comment]
See how the SignIn app created a default user: https://github.com/StarcounterSamples/SignIn/blob/master/src/SignIn/Helpers/SignInOut.cs#L19, and make sure that you double hash password.

**Comment by atifwaqar** [comment]
Thanks for the Update. My code works fine now. 
But do you have any suggestion for our Live server? because we can not delete and add all the users again. is there any modify password function which can fix the old passwords automatically?

**Comment by miyconst** [comment]
Unfortunately there is no function to "fix" password automatically as hash is a one way operation. 

- You can reset all the passwords and send it to the clients.
- You can modify SignIn app so it tries to sign in with a single hashed password in case of failure and later updates database.
- You can add an "Update my password" form where users will enter their current password and click update. Single hashed value will be checked against the database and if valid then update the database.
- You can keep using SignIn `3.x.x`.

**Comment by atifwaqar** [comment]
@miyconst Thanks for the information :+1:
