### ISSUE TITLE
version 4.0 - request review

### ISSUE THREAD

**Issue by miyconst** [StarcounterSamples/SignIn#22]
I have finished or almost finished the next version of SignIn app. It includes some major changes:

- New internal design.
- Restore password.
- Registration.
- User profile.
- Double password hashing.

The code is available in `version-4.0` branch, @warpech take a look please, if everything is fine I will merge to master branch.

**Comment by miyconst** [comment]
I don't think it's a good idea to push password of SMTP account, so you have to change the password before testing Restore password function.

**Comment by ubbeK** [comment]
I am not done testing but I did find one irregularity, the "forgot password"-btn adds a new Resore password section which is replaced by Sign-in if "SIGN-IN"-btn is pressed. This will result in a long list of  Sign-in sections.
![signin_forgotpw](https://cloud.githubusercontent.com/assets/8124023/14498379/83e2299c-019a-11e6-9310-019583c59d8e.gif)

**Comment by miyconst** [comment]
@ubbeK thank you for reporting. This issue is under investigation: https://github.com/StarcounterPrefabs/Launcher/issues/224.

**Comment by ubbeK** [comment]
SignInPage.html uses placeholder for input-tag **Username / email** while SignInFormPage.html uses **Username**. Cannot Sign-in using the email.
![signin_email](https://cloud.githubusercontent.com/assets/8124023/14522429/c90de030-022e-11e6-830d-73170c979a67.gif)

**Comment by ubbeK** [comment]
And also, shouldn't the **SIGN OUT**-btn always redirect the page to **/signin/signinuser** so that the "You dont have persmission to access this page" does not appear?

**Comment by miyconst** [comment]
>SignInPage.html uses placeholder for input-tag Username / email while SignInFormPage.html uses Username. Cannot Sign-in using the email.

Fixed.

>And also, shouldn't the SIGN OUT-btn always redirect the page to /signin/signinuser so that the "You dont have persmission to access this page" does not appear?

No. We never know what applications are running and which of them are available for anonymous users. We should notify about sign in state, but not redirect.

**Comment by ubbeK** [comment]
Done testing in Chrome. Cannot find anymore bugs.

**Comment by miyconst** [comment]
Released as SignIn `4.0.0`.
