### ISSUE TITLE
Fix BEM-style CSS in SignIn

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/SignIn#24]
This app generally follows BEM (https://github.com/Starcounter/Starcounter/issues/3450), but in few places applies global CSS rules, for example:

- https://github.com/StarcounterSamples/SignIn/blob/082d52c453c0a69f1e1c04036f761e2c04568d9b/src/SignIn/wwwroot/SignIn/viewmodels/SignInPage.html#L49-L61

There is also some inline style, for example:

- https://github.com/StarcounterSamples/SignIn/blob/082d52c453c0a69f1e1c04036f761e2c04568d9b/src/SignIn/wwwroot/SignIn/viewmodels/SignInPage.html#L74

Class `signin-popup_window` should be renamed to `signin-popup-window` in:

- https://github.com/StarcounterSamples/SignIn/blob/082d52c453c0a69f1e1c04036f761e2c04568d9b/src/SignIn/wwwroot/SignIn/viewmodels/SignInPage.html#L12

**Comment by miyconst** [comment]
Thank you for the issue. It's fixed now.
