### ISSUE TITLE
Hide/Remove SIGN IN button when registering

### ISSUE THREAD

**Issue by andwah** [StarcounterSamples/SignIn#25]
***I want to register***
![image](https://cloud.githubusercontent.com/assets/2656996/14565236/60a88c32-032a-11e6-8e08-24f683168504.png)

***I click `Registration` button***

![image](https://cloud.githubusercontent.com/assets/2656996/14565259/7d5e407e-032a-11e6-8588-d1e2123dda76.png)

Now i want to register and sign in.. so i click  `SIGN IN` and then im shown the sign in page again and have to renter everything again.

  Can the `SIGN IN` button be hidden to avoid letting the user pressing the wrong button?

**Comment by miyconst** [comment]
How would user navigate back to sign in, if he/she decided to not register?

**Comment by andwah** [comment]
the back button in browser.

**Comment by miyconst** [comment]
It's a common and good practice to keep Sign In button on the registration page.
For example stackoverflow: https://stackoverflow.com/users/signup

I can implement a better design, but not remove the button.

**Comment by andwah** [comment]
What feels normal If i enter the information on the Registration page and then Click the `Sign In` button?  What does the user expect to happen?   
I expect to be signed in if provided information is correct not to come to an Sign In page where i need to re-enter the info.

We can keep the sign in button but i think we should change it's behavior then.

**Comment by miyconst** [comment]
It's not a button, it's a link, and links are naturally point to another page.

I have changed the layout:

![image](https://cloud.githubusercontent.com/assets/6435556/14634364/dde79b80-0621-11e6-9389-847d94c23820.png)

**Comment by andwah** [comment]
Very Nice. now if feels more natural.
