### ISSUE TITLE
SignInFormPage stays open

### ISSUE THREAD

**Issue by ubbeK** [StarcounterSamples/SignIn#27]
The `SignInFormPage` stays open when clicking on *Registration* or *Forgot Password* links but not for *SignIn* and *SignOut* buttons. Shouldn´t the links act the same ways as the buttons? Is this the desired functionality?

![signinform](https://cloud.githubusercontent.com/assets/8124023/15010267/6c711dfc-11eb-11e6-97da-a7c8c0918a0e.gif)

**Comment by miyconst** [comment]
Thank you @ubbeK for the question, it's definitely a bug.

Now it's fixed with a new version of Sign In.
