### ISSUE TITLE
Issue in Logging-in

### ISSUE THREAD

**Issue by atifwaqar** [StarcounterSamples/SignIn#31]
I just updated all my apps (Signin, Launcher, UserAdmin), and i am using latest nightly build. and i am not able to login.

I debugged the issue, and this is what I found : 
![image](https://cloud.githubusercontent.com/assets/4388707/15286598/3de7a588-1b5e-11e6-8ad8-6f1ea5208fdc.png)

in above attachment, if I replace the value "d3b5e082eb4d89e837a81379616ddca22f6f14d2" to password string (which is "administrator99"), everything works fine, and i get logged in.

**Comment by miyconst** [comment]
@atifwaqar in the SignIn version `4.x.x` password is double hashed, first on the client side, then on the server side. See this issue for more details: https://github.com/StarcounterSamples/SignIn/issues/15.
