### ISSUE TITLE
You are signed in

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/SignIn#5]
Could we change the text to say *"You are signed in"*. 

The word "already" makes it look like an error message, not a welcome message.

<img width="528" alt="screenshot 2015-10-13 11 58 12" src="https://cloud.githubusercontent.com/assets/566463/10451692/03e5567a-71a2-11e5-9018-d868523332e1.png">

Or maybe it is intended as an error message?

**Comment by miyconst** [comment]
Fixed.

The new messages:

![image](https://cloud.githubusercontent.com/assets/6435556/10483851/d1826606-7281-11e5-88d5-11d9e2feb303.png)
