### ISSUE TITLE
Release git tags

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/SignIn#6]
For the last releases 3.1.2-3.1.4, a git tag was not created.

@miyconst can you create it according to the instructions? https://github.com/StarcounterSamples/AppStoreServer/wiki/How-to-publish-apps

When you do it, it will appear in https://github.com/StarcounterSamples/Launcher/releases

**Comment by miyconst** [comment]
I did not add the tags on purpose, because there were minor changes/fixes. I want to get somehow bug-free version of SignIn and then tag it.

Current version can be released though.

>When you do it, it will appear in https://github.com/StarcounterSamples/Launcher/releases

This is probably a typo, should be 
>When you do it, it will appear in https://github.com/StarcounterSamples/SignIn/releases

**Comment by miyconst** [comment]
Released as 3.1.5 with some more changes.
https://github.com/StarcounterSamples/SignIn/releases/tag/3.1.5

**Comment by warpech** [comment]
There is no rule saying that a minor change should not have a tag. 

Every release that increases the version number in `package.config` and lands in the app store should have a git tag as part of the process.

**Comment by miyconst** [comment]
Okay, will tag each version increase. Should I add the missing tags now?

**Comment by warpech** [comment]
Yes, please. Tags can be applied to previous commits with no problem.

**Comment by miyconst** [comment]
Done.
