### ISSUE TITLE
Signin does not redirect correctly, instead give a "workspace without appname"

### ISSUE THREAD

**Issue by malx122** [StarcounterSamples/SignIn#7]
After discussion, the bug might be within launcher or somewhere else but it is still a bug that affects Signin and there are workarounds!

**Comment by warpech** [comment]
Related: https://github.com/Starcounter/InvoiceDemo/issues/55

**Comment by warpech** [comment]
The "workspace without appname" error is now gone, but we still have a problem with showing a blank workspace. This is tracked in a separate issue: https://github.com/StarcounterSamples/SignIn/issues/12
